Module2 task1
htmlacademy-react/814025-what-to-watch-10 pull request #4
Opened 2022-07-26 16:10 UTC by NatalyLu

Created pages' components

2022-07-26 21:19 UTC, TchernyavskyDaniil requested changes
Есть парочка замечаний 👀

2022-07-26 21:19 UTC, TchernyavskyDaniil commented on project/src/index.tsx
> +const Promo = {
👀  

https://up.htmlacademy.ru/react/10/criteries#b7
![изображение](https://user-images.githubusercontent.com/29048318/181112019-ac1d7849-9b79-4ab1-92ea-069f5d5d63b1.png)

2022-07-26 21:19 UTC, TchernyavskyDaniil commented on project/src/components/app/app.tsx
> +type AppFilmProps = {
Лучше называть тип либо просто `Props`, либо `ComponentNameProps`
В твоем случае не совсем понятно зачем `Film`, возможно, ты использовала это слово, тк в типах есть объект `promoFilm`, но что делать если будет в типах много значений?)

2022-07-26 21:19 UTC, TchernyavskyDaniil commented on project/src/components/films-card/films-card.tsx
> +function FilmCard(): JSX.Element {
![изображение](https://user-images.githubusercontent.com/29048318/181112580-5751435a-2643-43b5-a4be-42cb2da4613f.png)
Так `FilmCard` или `FilmsCard`? 

Раз просят одной карточки фильма, то все же думаю `FilmCard`
![изображение](https://user-images.githubusercontent.com/29048318/181113788-d429bef8-7f8f-4810-bc7a-bb6871a7f0b7.png)

2022-07-26 21:19 UTC, TchernyavskyDaniil commented on project/src/pages/main/main.tsx
> +type AppFilmProps = {
Тут тоже с props типом как и выше 👀

2022-07-26 21:19 UTC, TchernyavskyDaniil commented on project/src/pages/main/main.tsx
> +            <FilmsCard />
А давай лучше такое сделаем пока через конструкцию 
`Array.from(Array(FILMS_CARD_COUNT).keys()).map(...)` или вы пока подобное не изучали?

2022-07-27 08:11 UTC, NatalyLu commented on project/src/index.tsx
> +const Promo = {
не очень понимаю теперь, как правильно, брала пример от сюда
https://github.com/htmlacademy-react/guess-melody-10/pull/2/commits/8baefb9a51351dea5e4231c7f801798fe3925bf6

![image](https://user-images.githubusercontent.com/45073400/181196395-274227ac-4954-4b96-b6c5-4459ba966a32.png)

2022-07-27 08:13 UTC, NatalyLu commented on project/src/index.tsx
> +const Promo = {
получается данные для фильма( name, genre и year), стоит написать прописными?

2022-07-27 11:27 UTC, NatalyLu commented on project/src/pages/main/main.tsx
> +            <FilmsCard />
Не проходили, но я думала об этом. Я добавила массив с фильмами и прокинула его везде через пропсы. Возникает вопрос, можно ли как-то упростить описание типов, очень много повторяющихся конструкций начинает появляться. или это будет рассмотрено в дальнейших разделах?

2022-07-27 11:34 UTC, TchernyavskyDaniil commented on project/src/index.tsx
> +const Promo = {
Давай оставим пока твой вариант. Уточню в учительской насколько это верно они сделали согласно их пунктам приема работы

2022-07-27 11:41 UTC, TchernyavskyDaniil commented on project/src/pages/main/main.tsx
> +            <FilmsCard />
https://github.com/htmlacademy-react/guess-melody-10/tree/master/project/src/types ты можешь дублирующие типы вынести сюда и импортить

2022-07-27 15:01 UTC, TchernyavskyDaniil commented on project/src/pages/film/film.tsx
> +type FilmCardsProps = {
Для `Film` компонента все же больше подходит `FilmProps` тогда
Да и к тому же такой тип уже есть в нужном месте 👀 
![изображение](https://user-images.githubusercontent.com/29048318/181280705-dfb22f50-4346-46a6-bd92-6ba6987bb0c5.png)

2022-07-27 15:03 UTC, TchernyavskyDaniil commented on project/src/index.tsx
> +const Promo = {
Про это пока не ответили. Раз так делает преподаватель, то я думаю ничего страшного. Значит надо написать каждый ключ объекта в UPPER_SNAKE_CASE сейчас

2022-07-27 17:42 UTC, TchernyavskyDaniil commented on project/src/types/types.tsx
> +export type Film = {
Почему у тебя в type `Film` содержится объект `film`? Film же состоит из link и name. 
`film` - это prop, пусть он будет на уровне объявленных типов `Props` компонента нужного

2022-07-27 17:42 UTC, TchernyavskyDaniil commented on project/src/types/types.tsx
> +  films: {LINK: string, NAME: string}[],
И тогда если подправить тип `Film` удобно получится
```ts
films: Film[]
```

2022-07-27 17:42 UTC, TchernyavskyDaniil commented on project/src/types/types.tsx
> +export type PromoFilm = {
Тут тоже не верно. Такая же ошибка как с `Film`. Как будто ты так хотела описать типы Props заодно. Но лучше указывать Props только в файле компонента. Тк они нужны только ему. 

```ts
type ComponentNameProps = {
  films: Films;
  promoFilm: PromoFilm
}
```

2022-07-27 17:42 UTC, TchernyavskyDaniil commented on project/src/index.tsx
> +    LINK: 'img/fantastic-beasts-the-crimes-of-grindelwald.jpg',
А вот это уже странно смотрится в uppercase. Я такое впервые вижу. Я думаю `Promo` сделали в uppercase из-за того, что это перечисление связанных констант

![изображение](https://user-images.githubusercontent.com/29048318/181313366-242b86e7-a982-47d4-aa6d-3dc0212c43eb.png)

А в твоем случае `Promo` и `Films` это значения, которые сразу идут в props компонента. Значит 
1) Уберем все uppercase для NAME, GENDER, YEAR, LINK
2) Promo и Films укажем в UPPER_SNAKE_CASE
3) в `App` передадим props `PROMO` и `FILMS`

И в типах не забудь подправить

2022-07-27 17:45 UTC, TchernyavskyDaniil commented on project/src/types/types.tsx
> +export type PromoFilm = {
Плюс мы так успешно покроем критерий

![изображение](https://user-images.githubusercontent.com/29048318/181318024-689e2e90-ee7f-4df5-adae-b20c94096daf.png)

2022-07-27 17:59 UTC, merged

2022-07-27 18:06 UTC, NatalyLu commented on project/src/types/types.tsx
> +  films: {LINK: string, NAME: string}[],
Логично

2022-07-27 19:21 UTC, TchernyavskyDaniil commented on project/src/index.tsx
> +    LINK: 'img/fantastic-beasts-the-crimes-of-grindelwald.jpg',
тут если что уточнение по 3 пункту, PROMO, FILMS это константы, а props `promoFilm` и `film` сохранят свое название