Module6 task1
htmlacademy-react/814025-what-to-watch-10 pull request #9
Opened 2022-08-15 17:54 UTC by NatalyLu

- Fixed previous mistakes
- Corrected mockes
- Connected redux
- Added components for films' catalog

2022-08-16 10:30 UTC, TchernyavskyDaniil requested changes

2022-08-16 10:30 UTC, TchernyavskyDaniil commented on project/src/const.ts
> +export const defaultGenre = 'All genres';
Не забываем следить за критериями :) Без них при всем желании не примут работу
https://up.htmlacademy.ru/react/10/criteries#b7

2022-08-16 10:30 UTC, TchernyavskyDaniil commented on project/src/index.tsx
> +      <App promoFilm={promo} films={films} reviews={reviews} />
![изображение](https://user-images.githubusercontent.com/29048318/184857759-0bdbcdcb-5767-4def-b898-e276d3d767b7.png)
А зачем тут prop `films` если такой же есть в сторе? В чем их отличия?

2022-08-16 10:30 UTC, TchernyavskyDaniil commented on project/src/pages/film/film.tsx
> +  films: FilmsData;
Data мне кажется в целом лишний постфикс. Это в любом случае какие - то данные) А почему решила начать добавлять?

2022-08-16 10:30 UTC, TchernyavskyDaniil commented on project/src/store/action.ts
> +export const changingGenre = createAction( 'films/changingGenre',(genre) => ({payload: genre}) );
Не очень понял зачем тут prepare action (2 аргумент). То, что ты передала в chainginGenre и так запишется в payload
Возможно ты это сделала тк ТС или линтер ругался. Тут надо просто тип объявить :)
`createAction<string>( 'films/changingGenre')`

2022-08-16 16:18 UTC, NatalyLu commented on project/src/index.tsx
> +      <App promoFilm={promo} films={films} reviews={reviews} />
это я ещё не успела поправить, шла чисто по заданию. Поправлю везде на стор

2022-08-16 18:49 UTC, NatalyLu commented on project/src/pages/film/film.tsx
> +  films: FilmsData;
у меня в типах уже есть Film, понадобилось ещё один тип для фильма, так появилась FilmData и FilmsData, сейчас я избавилась от добавочного типа, поэтому удалю FilmData. С названиями у меня всегда было туго )

2022-08-16 19:09 UTC, NatalyLu commented on project/src/store/action.ts
> +export const changingGenre = createAction( 'films/changingGenre',(genre) => ({payload: genre}) );
угу, с типом не ругается, спасибо!

2022-08-16 19:17 UTC, NatalyLu commented on project/src/store/reducer.ts
> +const getFilmsByGenre = (genre: string, allfilms: FilmsData) => {
ругается, что уже есть films
![image](https://user-images.githubusercontent.com/45073400/184963597-1c0dac23-cc6c-499f-ac50-784898b4a55b.png)

2022-08-17 08:18 UTC, TchernyavskyDaniil approved these changes

2022-08-17 08:18 UTC, TchernyavskyDaniil commented on project/src/components/film-catalog/film-catalog.tsx
> +  const isFilms = films.length - someFilteredFilms.length;
Тут к сожалению будет тип number, и isSomething не подойдет) Если хочешь, то можно в Boolean обернуть твое суммарное количество фильмов 

![изображение](https://user-images.githubusercontent.com/29048318/185068147-00b57286-696a-4828-8eff-f67f3bbe2494.png)

2022-08-17 08:18 UTC, TchernyavskyDaniil commented on project/src/components/film-catalog/film-catalog.tsx
> +      {(isFilms) ? <ShowMore onClick={handleButtonClick}/> : null }
И если ты обернешь в Boolean, то тут можно сделать короче запись
`isFilms && <ShowMore onClick={handleButtonClick}/>` и не будет никакого 0 выводиться :)

2022-08-17 08:18 UTC, TchernyavskyDaniil commented on project/src/components/tabs/overview-tab.tsx
> +  const review = useAppSelector((store) => store.reviews)[0];
review можно так же в сторе будет хранить, либо прямо 
`useAppSelector((store) => store.reviews[0])`
Так будет немного правильней, тк все же подобные действия с данными как раз задача работы на уровне redux. Те же селекторы (селектор - это то, что ты написала store => store.reviews внутри хука) частично для этого и нужны, чтобы получать нужный формат или тип данных из исходных

2022-08-17 08:18 UTC, TchernyavskyDaniil commented on project/src/store/reducer.ts
> +  filmsArr.map(
Тут больше forEach подойдет
map больше служит для получения нового массива из исходного

2022-08-17 08:19 UTC, merged